name: ESP32 Firmware Build and Tag
on:
  push:
    branches:
      - 'main'
    tags: []
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc
      - uses: n-vr/setup-platformio-action@v1
      - name: Create dummy credentials
        run: |
          cat <<'EOF' > src/credentials.h
          #pragma once
          extern const char* WIFI_SSID;
          extern const char* WIFI_PASSWORD;
          extern const char* OTA_PASSWORD;
          extern const char* PUSHOVER_TOKEN;
          extern const char* PUSHOVER_USER;
          extern const char* MQTT_USER;
          extern const char* MQTT_PASSWORD;
          EOF
          cat <<'EOF' > src/credentials.cpp
          #include "credentials.h"
          const char* WIFI_SSID = "";
          const char* WIFI_PASSWORD = "";
          const char* OTA_PASSWORD = "";
          const char* PUSHOVER_TOKEN = "";
          const char* PUSHOVER_USER = "";
          const char* MQTT_USER = "";
          const char* MQTT_PASSWORD = "";
          EOF
      - name: Build all firmware configurations
        id: build
        run: |
          # Build MQTT-only configuration (default)
          echo "Building MQTT-only configuration..."
          pio run --environment esp32-c3-devkitm-1 | tee build-mqtt.log
          MQTT_RAM=$(grep -Eo 'RAM:.*' build-mqtt.log | grep -Eo '[0-9.]+%' | head -1)
          MQTT_FLASH=$(grep -Eo 'Flash:.*' build-mqtt.log | grep -Eo '[0-9.]+%' | head -1)
          MQTT_FLASH_BYTES=$(grep -Eo 'Flash:.*' build-mqtt.log | grep -Eo '[0-9,]+ bytes' | head -1 | tr -d ',')
          
          # Build WebServer-only configuration
          echo "Building WebServer-only configuration..."
          pio run --environment esp32-c3-devkitm-1-webserver | tee build-webserver.log
          WEB_RAM=$(grep -Eo 'RAM:.*' build-webserver.log | grep -Eo '[0-9.]+%' | head -1)
          WEB_FLASH=$(grep -Eo 'Flash:.*' build-webserver.log | grep -Eo '[0-9.]+%' | head -1)
          WEB_FLASH_BYTES=$(grep -Eo 'Flash:.*' build-webserver.log | grep -Eo '[0-9,]+ bytes' | head -1 | tr -d ',')
          
          # Build Both configurations
          echo "Building Both MQTT and WebServer configuration..."
          pio run --environment esp32-c3-devkitm-1-both | tee build-both.log
          BOTH_RAM=$(grep -Eo 'RAM:.*' build-both.log | grep -Eo '[0-9.]+%' | head -1)
          BOTH_FLASH=$(grep -Eo 'Flash:.*' build-both.log | grep -Eo '[0-9.]+%' | head -1)
          BOTH_FLASH_BYTES=$(grep -Eo 'Flash:.*' build-both.log | grep -Eo '[0-9,]+ bytes' | head -1 | tr -d ',')
          
          # Output all values
          echo "mqtt_ram=$MQTT_RAM" >> $GITHUB_OUTPUT
          echo "mqtt_flash=$MQTT_FLASH" >> $GITHUB_OUTPUT
          echo "mqtt_flash_bytes=$MQTT_FLASH_BYTES" >> $GITHUB_OUTPUT
          echo "web_ram=$WEB_RAM" >> $GITHUB_OUTPUT
          echo "web_flash=$WEB_FLASH" >> $GITHUB_OUTPUT
          echo "web_flash_bytes=$WEB_FLASH_BYTES" >> $GITHUB_OUTPUT
          echo "both_ram=$BOTH_RAM" >> $GITHUB_OUTPUT
          echo "both_flash=$BOTH_FLASH" >> $GITHUB_OUTPUT
          echo "both_flash_bytes=$BOTH_FLASH_BYTES" >> $GITHUB_OUTPUT
          
          echo "All builds completed successfully!"
      - name: Get main branch memory usage (for comparison)
        if: github.event_name == 'pull_request'
        id: main-build
        run: |
          # Try to get main branch memory usage for comparison
          # This is a best-effort comparison - if it fails, we'll skip comparisons
          set +e
          
          # Fetch main branch
          git fetch origin main:main || true
          
          # Save current state
          CURRENT_SHA=$(git rev-parse HEAD)
          
          # Try to checkout main and build for comparison
          if git checkout main 2>/dev/null; then
            echo "Building main branch for comparison..."
            
            # Create dummy credentials for main branch build
            cat <<'EOF' > src/credentials.h
          #pragma once
          extern const char* WIFI_SSID;
          extern const char* WIFI_PASSWORD;
          extern const char* OTA_PASSWORD;
          extern const char* PUSHOVER_TOKEN;
          extern const char* PUSHOVER_USER;
          extern const char* MQTT_USER;
          extern const char* MQTT_PASSWORD;
          EOF
            cat <<'EOF' > src/credentials.cpp
          #include "credentials.h"
          const char* WIFI_SSID = "";
          const char* WIFI_PASSWORD = "";
          const char* OTA_PASSWORD = "";
          const char* PUSHOVER_TOKEN = "";
          const char* PUSHOVER_USER = "";
          const char* MQTT_USER = "";
          const char* MQTT_PASSWORD = "";
          EOF
            
            # Build main branch (try both old and new format)
            if pio run 2>/dev/null | tee main-build.log; then
              MAIN_FLASH_BYTES=$(grep -Eo 'Flash:.*' main-build.log | grep -Eo '[0-9,]+ bytes' | head -1 | tr -d ',')
              MAIN_RAM=$(grep -Eo 'RAM:.*' main-build.log | grep -Eo '[0-9.]+%' | head -1)
              MAIN_FLASH=$(grep -Eo 'Flash:.*' main-build.log | grep -Eo '[0-9.]+%' | head -1)
              echo "main_flash_bytes=$MAIN_FLASH_BYTES" >> $GITHUB_OUTPUT
              echo "main_ram=$MAIN_RAM" >> $GITHUB_OUTPUT
              echo "main_flash=$MAIN_FLASH" >> $GITHUB_OUTPUT
              echo "has_main_comparison=true" >> $GITHUB_OUTPUT
              echo "Main branch build successful for comparison"
            else
              echo "Main branch build failed, skipping comparison"
              echo "has_main_comparison=false" >> $GITHUB_OUTPUT
            fi
            
            # Return to PR branch
            git checkout $CURRENT_SHA
          else
            echo "Could not checkout main branch, skipping comparison"
            echo "has_main_comparison=false" >> $GITHUB_OUTPUT
          fi
          
          set -e
      - name: Find pull request
        if: github.event_name == 'pull_request'
        id: pr
        uses: jwalton/gh-find-current-pr@v1
      - name: Find existing comment
        if: github.event_name == 'pull_request'
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '**ESP32 Firmware Build Report**'
      - name: Create comprehensive build report
        if: github.event_name == 'pull_request'
        id: report
        run: |
          # Function to calculate percentage difference and format with emoji
          calculate_diff() {
            local current=$1
            local main=$2
            local has_comparison=$3
            
            if [ "$has_comparison" = "true" ] && [ -n "$current" ] && [ -n "$main" ] && [ "$main" != "0" ]; then
              # Calculate percentage difference
              local diff=$(echo "scale=1; ($current - $main) * 100 / $main" | bc -l 2>/dev/null || echo "0")
              local abs_diff=$(echo "$diff" | sed 's/-//')
              
              if (( $(echo "$diff > 1" | bc -l) )); then
                echo "📈 +${abs_diff}%"
              elif (( $(echo "$diff < -1" | bc -l) )); then
                echo "📉 -${abs_diff}%"
              else
                echo "➡️ ~0%"
              fi
            else
              echo "➖ N/A"
            fi
          }
          
          # Function to format bytes with commas
          format_bytes() {
            echo $1 | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta'
          }
          
          # Get comparison values
          HAS_MAIN="${{ steps.main-build.outputs.has_main_comparison }}"
          MAIN_FLASH_BYTES="${{ steps.main-build.outputs.main_flash_bytes }}"
          MAIN_RAM="${{ steps.main-build.outputs.main_ram }}"
          MAIN_FLASH="${{ steps.main-build.outputs.main_flash }}"
          
          # Calculate differences for each configuration
          MQTT_FLASH_DIFF=$(calculate_diff "${{ steps.build.outputs.mqtt_flash_bytes }}" "$MAIN_FLASH_BYTES" "$HAS_MAIN")
          MQTT_RAM_DIFF=$(calculate_diff "$(echo '${{ steps.build.outputs.mqtt_ram }}' | sed 's/%//')" "$(echo '$MAIN_RAM' | sed 's/%//')" "$HAS_MAIN")
          
          WEB_FLASH_DIFF=$(calculate_diff "${{ steps.build.outputs.web_flash_bytes }}" "$MAIN_FLASH_BYTES" "$HAS_MAIN")
          WEB_RAM_DIFF=$(calculate_diff "$(echo '${{ steps.build.outputs.web_ram }}' | sed 's/%//')" "$(echo '$MAIN_RAM' | sed 's/%//')" "$HAS_MAIN")
          
          BOTH_FLASH_DIFF=$(calculate_diff "${{ steps.build.outputs.both_flash_bytes }}" "$MAIN_FLASH_BYTES" "$HAS_MAIN")
          BOTH_RAM_DIFF=$(calculate_diff "$(echo '${{ steps.build.outputs.both_ram }}' | sed 's/%//')" "$(echo '$MAIN_RAM' | sed 's/%//')" "$HAS_MAIN")
          
          # Output variables for the comment
          echo "mqtt_flash_diff=$MQTT_FLASH_DIFF" >> $GITHUB_OUTPUT
          echo "mqtt_ram_diff=$MQTT_RAM_DIFF" >> $GITHUB_OUTPUT
          echo "web_flash_diff=$WEB_FLASH_DIFF" >> $GITHUB_OUTPUT
          echo "web_ram_diff=$WEB_RAM_DIFF" >> $GITHUB_OUTPUT
          echo "both_flash_diff=$BOTH_FLASH_DIFF" >> $GITHUB_OUTPUT
          echo "both_ram_diff=$BOTH_RAM_DIFF" >> $GITHUB_OUTPUT
          
          # Format bytes for display
          echo "mqtt_flash_formatted=$(format_bytes ${{ steps.build.outputs.mqtt_flash_bytes }})" >> $GITHUB_OUTPUT
          echo "web_flash_formatted=$(format_bytes ${{ steps.build.outputs.web_flash_bytes }})" >> $GITHUB_OUTPUT
          echo "both_flash_formatted=$(format_bytes ${{ steps.build.outputs.both_flash_bytes }})" >> $GITHUB_OUTPUT
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |
            ## 🚀 ESP32 Firmware Build Report
            
            📅 **Latest Build:** ${{ github.event.head_commit.timestamp || github.event.pull_request.updated_at }}  
            🔗 **Commit:** [`${{ github.sha }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            
            ---
            
            ### 📊 Build Configurations
            
            | Configuration | Flash Usage | RAM Usage | vs Main |
            |---|---|---|---|
            | 🏠 **MQTT Only** *(default)* | `${{ steps.report.outputs.mqtt_flash_formatted }} bytes` (`${{ steps.build.outputs.mqtt_flash }}`) | `${{ steps.build.outputs.mqtt_ram }}` | ${{ steps.report.outputs.mqtt_flash_diff }} |
            | 🌐 **WebServer Only** | `${{ steps.report.outputs.web_flash_formatted }} bytes` (`${{ steps.build.outputs.web_flash }}`) | `${{ steps.build.outputs.web_ram }}` | ${{ steps.report.outputs.web_flash_diff }} |
            | 🔄 **Both Features** | `${{ steps.report.outputs.both_flash_formatted }} bytes` (`${{ steps.build.outputs.both_flash }}`) | `${{ steps.build.outputs.both_ram }}` | ${{ steps.report.outputs.both_flash_diff }} |
            
            ---
            
            ### 💾 Memory Optimization Summary
            
            #### 🏠 MQTT-Only Build *(Recommended for Home Assistant)*
            - **Flash:** ${{ steps.build.outputs.mqtt_flash }} (${{ steps.report.outputs.mqtt_flash_diff }} from main)
            - **RAM:** ${{ steps.build.outputs.mqtt_ram }} (${{ steps.report.outputs.mqtt_ram_diff }} from main)
            - **Features:** Home Assistant integration, Telnet console, OTA updates
            - **Environment:** `esp32-c3-devkitm-1`
            
            #### 🌐 WebServer-Only Build *(Web Interface)*
            - **Flash:** ${{ steps.build.outputs.web_flash }} (${{ steps.report.outputs.web_flash_diff }} from main)
            - **RAM:** ${{ steps.build.outputs.web_ram }} (${{ steps.report.outputs.web_ram_diff }} from main)
            - **Features:** Web interface, API endpoints, Telnet console, OTA updates
            - **Environment:** `esp32-c3-devkitm-1-webserver`
            
            #### 🔄 Full Feature Build *(Everything)*
            - **Flash:** ${{ steps.build.outputs.both_flash }} (${{ steps.report.outputs.both_flash_diff }} from main)
            - **RAM:** ${{ steps.build.outputs.both_ram }} (${{ steps.report.outputs.both_ram_diff }} from main)
            - **Features:** All features enabled (equivalent to previous versions)
            - **Environment:** `esp32-c3-devkitm-1-both`
            
            ---
            
            ### 🛠️ Build Commands
            
            ```bash
            # Default (MQTT-only)
            ./upload_and_monitor.sh
            
            # WebServer-only  
            ./upload_and_monitor.sh webserver
            
            # Both features
            ./upload_and_monitor.sh both
            ```
            
            <details>
            <summary>📈 Legend</summary>
            
            - 📈 = Increase from main branch
            - 📉 = Decrease from main branch  
            - ➡️ = Minimal change (~0%)
            - ➖ = No comparison data available
            
            </details>
            
            *🤖 Updated automatically with latest build information*
      - name: Extract version
        if: github.event_name == 'push'
        id: get_version
        run: |
          VERSION=$(sed -n 's/^const char\* firmwareVersion = "\(.*\)";/\1/p' src/config.cpp)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Check for source code changes
        id: check_changes
        if: github.event_name == 'push'
        run: |
          # Only tag commits that contain source code changes, not infrastructure-only changes
          # Source paths: src/, data/ (ESP32 core functionality)
          # Infrastructure paths: .github/, k8s/, scripts/, web/, platformio.ini, README.md, etc.
          
          # Get the list of changed files in this push
          # For merge commits, compare with the first parent to get all changes from the merged branch
          if [ $(git rev-list --count ${{ github.event.before }}..${{ github.sha }}) -gt 1 ]; then
            # Multiple commits, likely a merge - check all files changed
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }})
          else
            # Single commit - check files changed in this commit
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          fi
          
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Define source code paths that should trigger tagging
          SOURCE_PATHS="^(src/|data/)"
          
          # Check if any changed files match source code paths
          HAS_SOURCE_CHANGES=false
          while IFS= read -r file; do
            if echo "$file" | grep -qE "$SOURCE_PATHS"; then
              echo "Source code file changed: $file"
              HAS_SOURCE_CHANGES=true
            fi
          done <<< "$CHANGED_FILES"
          
          echo "has_source_changes=$HAS_SOURCE_CHANGES" >> $GITHUB_OUTPUT
          
          if [ "$HAS_SOURCE_CHANGES" = "true" ]; then
            echo "✅ Source code changes detected - will proceed with tagging"
          else
            echo "ℹ️ Only infrastructure changes detected - skipping tagging"
          fi
      - name: Tag commit
        if: success() && github.event_name == 'push' && steps.check_changes.outputs.has_source_changes == 'true'
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.get_version.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}