name: Build and Tag

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: n-vr/setup-platformio-action@v1
      - name: Create fake credentials
        run: |
          cat <<'EOF' > src/credentials.cpp
          #include "credentials.h"
          const char* WIFI_SSID = "";
          const char* WIFI_PASSWORD = "";
          const char* OTA_PASSWORD = "";
          const char* PUSHOVER_TOKEN = "";
          const char* PUSHOVER_USER = "";
          const char* MQTT_SERVER = "";
          const int MQTT_PORT = 1883;
          const char* MQTT_USER = "";
          const char* MQTT_PASSWORD = "";
          EOF
      - uses: karniv00l/platformio-run-action@v1
